### ISSUE TITLE
M104 issue with new firmware 2.8.4

### ISSUE THREAD

**Issue by AndreaCCIE** [Mrnt/OctoPrint-FlashForge#77]
Today my printer installed the firmware 2.8.4.
It seems that since then the M104 command gets ignored/overridden, only when passing through serial. In this case, the temperature is ALWAYS automatically set to 180 regardless of what's in the g-code.
It works correctly if the file is printed via USB.

Is this a problem with OctoPrint or with the Plugin?

The problem only appears when I send the gcode via CURA or upload through OctoPI "Upload to SD" command.
If I stick a USB key with the same file into the USB printer port, it works correctly.

I can see the printing temperature set to 180 even if the gcode shows M104 S230 T0:

2021-08-31 08:52:44,586 - Recv: MachineStatus: BUILDING_FROM_SD
2021-08-31 08:52:44,587 - Recv: MoveMode: READY
2021-08-31 08:52:44,602 - Recv: Status: S:0 L:0 J:0 F:0
2021-08-31 08:52:44,617 - Recv: ok
2021-08-31 08:52:44,621 - Send: M105
2021-08-31 08:52:44,622 - Recv: CMD M27 Received.
2021-08-31 08:52:44,627 - Recv: SD printing byte 0/1000
2021-08-31 08:52:44,633 - Recv: ok
2021-08-31 08:52:44,645 - Recv: CMD M105 Received.
2021-08-31 08:52:44,656 - Recv: T0:204 /180 B:0/0

**Comment by Mrnt** [comment]
Sorry for the delay in responding!

What printer is this?
It is hard to say what is going on from the snippet you posted - is there any more temperature information in the log showing temperature changes and/or M104 temperature commands? 

From the snippet you posted it appears that the printer did set the extruder temperature above 180 since you are getting the response `Recv: T0:204 /180 B:0/0` indicating that the extruder is at 204, but if you had set it to 230 then it appears the printer initially tried to heat the extruder to 230 then the temperature somehow got set to 180.

If you are uploading a gcode file through OctoPi using the "Upload to SD" card then neither OctoPi or this plugin touches the code - it is passed directly to the printer in much the same manner as when you do a USB upload from FlashPrint to the printer. Therefore, if that file was generated using FlashPrint and you are having an issue I would recommend sending the same file directly from FlashPrint to the printer to verify the behaviour. If the file was generated using Cura then I would suggest looking at the gcode in the file for something that may be resetting the temperature. There is a somewhat complete reference of the gcode for FlashForge printers [here](https://github.com/Mrnt/OctoPrint-FlashForge/wiki/G-Code-Reference#m105---get-extruder-bed-temperatures), and you will note that there are differences between how some commands are interpreted by FlashForge vs Marlin printers.
